import type { Metadata, Viewport } from "next";
import { useFonts } from "./font";
import "./globals.scss";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Next.js App",
    description: "Generated by create next app",
    keywords: [
      "Next.js",
      "React",
      "JavaScript",
      "TypeScript",
      "SCSS",
      "CSS",
      "HTML",
    ],
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "rgba(0, 0, 0, 1)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontClasses = useFonts();
  return (
    <html lang="en">
      <body className={fontClasses}>{children}</body>
    </html>
  );
}
